### ISSUE TITLE
Unclear how to use Mock from rustdoc

### ISSUE THREAD

**Issue by antifuchs** [nuclearfurnace/quanta#6]
Hi there, I just stumbled over quanta in search for a mockable time source for my crate, https://crates.io/crates/ratelimit_meter - it seems like a great match for what I'm trying to do over there!

Now, I'd like to figure out if I could make a time source for the rate-limiter that can be mocked for tests, and just reading the [rustdoc for Mock](https://docs.rs/quanta/0.3.0/quanta/struct.Mock.html), I am not sure how to proceed. Do you have an example that I could steal^H^H^H^H^Hreference? (:

Thanks!

**Comment by antifuchs** [comment]
Oh gosh, and literally 5 minutes later, I found [`Clock.mock`](https://docs.rs/quanta/0.3.0/quanta/struct.Clock.html#method.mock). Sorry for the noise.

**Comment by tobz** [comment]
No problem!  Glad you figured it out. :D
